name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - python=3.10
  - pandas=2.1.3
  - pip=23.3.1
  - ydata-profiling=4.6.4
  - ipywidgets=8.0.4
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.2